//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Gio_Cha.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCompany
    {
        public long COMPANY_ID { get; set; }
        public string COMPANY_CD { get; set; }
        public string COMPANY_NAME { get; set; }
        public Nullable<decimal> COMPANY_LAT { get; set; }
        public Nullable<decimal> COMPANY_LNG { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string LINK_MAP { get; set; }
        public string COMPANY_PHONE { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string LOGO { get; set; }
        public string FACE_PAGE { get; set; }
        public string DEL_FLG { get; set; }
        public Nullable<System.DateTime> INS_DATE { get; set; }
        public Nullable<long> INS_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public Nullable<long> UPD_USER_ID { get; set; }
    }
}
