
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Web_Gio_Cha.EF
{

using System;
    using System.Collections.Generic;
    
public partial class TblMenuContent
{

    public int ID { get; set; }

    public string Menu_Name { get; set; }

    public string Menu_Content { get; set; }

    public Nullable<bool> Status { get; set; }

    public string del_flg { get; set; }

}

}
