//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Gio_Cha.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPromotion
    {
        public long id { get; set; }
        public string PromotionName { get; set; }
        public Nullable<decimal> PriceMin { get; set; }
        public Nullable<decimal> PriceMax { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string del_flg { get; set; }
    }
}
