//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Gio_Cha.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Gio_Cha.Resources.AdminLabel", typeof(AdminLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại List.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Category.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string CityDisplay {
            get {
                return ResourceManager.GetString("CityDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh, thành phố.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự .
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã quận huyện.
        /// </summary>
        public static string DistricCode {
            get {
                return ResourceManager.GetString("DistricCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quận huyện.
        /// </summary>
        public static string DistricName {
            get {
                return ResourceManager.GetString("DistricName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quận huyện.
        /// </summary>
        public static string DistrictListTitle {
            get {
                return ResourceManager.GetString("DistrictListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí quận huyện.
        /// </summary>
        public static string DistrictRegisterTitle {
            get {
                return ResourceManager.GetString("DistrictRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa quận huyện.
        /// </summary>
        public static string DistricUpdateTitle {
            get {
                return ResourceManager.GetString("DistricUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string lblContent {
            get {
                return ResourceManager.GetString("lblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string lblDetail {
            get {
                return ResourceManager.GetString("lblDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá.
        /// </summary>
        public static string lblDiscount {
            get {
                return ResourceManager.GetString("lblDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tin tức.
        /// </summary>
        public static string lblEditNews {
            get {
                return ResourceManager.GetString("lblEditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ưu tiên.
        /// </summary>
        public static string lblHot {
            get {
                return ResourceManager.GetString("lblHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh minh họa.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng ký.
        /// </summary>
        public static string lblInsertDate {
            get {
                return ResourceManager.GetString("lblInsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đăng kí.
        /// </summary>
        public static string lblInsertName {
            get {
                return ResourceManager.GetString("lblInsertName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang hiển thị.
        /// </summary>
        public static string lblMenuCode {
            get {
                return ResourceManager.GetString("lblMenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ meta title.
        /// </summary>
        public static string lblMetaTitle {
            get {
                return ResourceManager.GetString("lblMetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá .
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá gốc.
        /// </summary>
        public static string lblPriceBefore {
            get {
                return ResourceManager.GetString("lblPriceBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mại.
        /// </summary>
        public static string lblPromotion {
            get {
                return ResourceManager.GetString("lblPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string lblQuatity {
            get {
                return ResourceManager.GetString("lblQuatity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng kí tin tức.
        /// </summary>
        public static string lblRegisterNews {
            get {
                return ResourceManager.GetString("lblRegisterNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh đại diện.
        /// </summary>
        public static string lblSelectImage {
            get {
                return ResourceManager.GetString("lblSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhiều ảnh.
        /// </summary>
        public static string lblSelectMoreImage {
            get {
                return ResourceManager.GetString("lblSelectMoreImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string lblTitleNews {
            get {
                return ResourceManager.GetString("lblTitleNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string lblToDate {
            get {
                return ResourceManager.GetString("lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string lblUnit {
            get {
                return ResourceManager.GetString("lblUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        public static string lblUpdateDate {
            get {
                return ResourceManager.GetString("lblUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người cập nhật.
        /// </summary>
        public static string lblUpdateUser {
            get {
                return ResourceManager.GetString("lblUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nội dung trang.
        /// </summary>
        public static string MenuPageEditTitle {
            get {
                return ResourceManager.GetString("MenuPageEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quản lí trang.
        /// </summary>
        public static string MenuPageListTitle {
            get {
                return ResourceManager.GetString("MenuPageListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nội dung trang.
        /// </summary>
        public static string MenuPageRegisterTitle {
            get {
                return ResourceManager.GetString("MenuPageRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập để tiếp tục!.
        /// </summary>
        public static string MessessLogin {
            get {
                return ResourceManager.GetString("MessessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin tức.
        /// </summary>
        public static string NewsListTitle {
            get {
                return ResourceManager.GetString("NewsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá ship.
        /// </summary>
        public static string PriceShip {
            get {
                return ResourceManager.GetString("PriceShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách Category sản phẩm.
        /// </summary>
        public static string ProductCategoryListTitle {
            get {
                return ResourceManager.GetString("ProductCategoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký Category sản phẩm.
        /// </summary>
        public static string ProductCategoryRegisterTitle {
            get {
                return ResourceManager.GetString("ProductCategoryRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa Category sản phẩm.
        /// </summary>
        public static string ProductCategoryUpdate {
            get {
                return ResourceManager.GetString("ProductCategoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sản phẩm.
        /// </summary>
        public static string ProductListTitle {
            get {
                return ResourceManager.GetString("ProductListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký sản phẩm.
        /// </summary>
        public static string ProductRegisterTitle {
            get {
                return ResourceManager.GetString("ProductRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa sản phẩm.
        /// </summary>
        public static string ProductUpdate {
            get {
                return ResourceManager.GetString("ProductUpdate", resourceCulture);
            }
        }
    }
}
