//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Gio_Cha.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Gio_Cha.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi trong quá trình xử lí!.
        /// </summary>
        public static string CancelFailed {
            get {
                return ResourceManager.GetString("CancelFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã hủy đơn thành công!.
        /// </summary>
        public static string CancelSuccess {
            get {
                return ResourceManager.GetString("CancelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối đa {1} kí tự!.
        /// </summary>
        public static string CheckMaxLength {
            get {
                return ResourceManager.GetString("CheckMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối thiểu {1} kí tự!.
        /// </summary>
        public static string CheckMinLength {
            get {
                return ResourceManager.GetString("CheckMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá  {1} !.
        /// </summary>
        public static string CheckValueMax {
            get {
                return ResourceManager.GetString("CheckValueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn chuyển sang màn hình List?.
        /// </summary>
        public static string ConfirmBack {
            get {
                return ResourceManager.GetString("ConfirmBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa đã nhâp?.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xóa {0} ?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra!.
        /// </summary>
        public static string ConfirmDeleteError {
            get {
                return ResourceManager.GetString("ConfirmDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thoát?.
        /// </summary>
        public static string ConfirmLogoutAccount {
            get {
                return ResourceManager.GetString("ConfirmLogoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn cập nhập thanh toán cho hóa đơn ?.
        /// </summary>
        public static string ConfirmPayment {
            get {
                return ResourceManager.GetString("ConfirmPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn {0}?.
        /// </summary>
        public static string ConfirmSubmitData {
            get {
                return ResourceManager.GetString("ConfirmSubmitData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa bản ghi!.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tối đa 50 kí tự!.
        /// </summary>
        public static string DistrictNameLength {
            get {
                return ResourceManager.GetString("DistrictNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thất bại!.
        /// </summary>
        public static string FailedPayment {
            get {
                return ResourceManager.GetString("FailedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng!.
        /// </summary>
        public static string IncorrectFormat {
            get {
                return ResourceManager.GetString("IncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn hủy đơn?.
        /// </summary>
        public static string msgConfirmCancel {
            get {
                return ResourceManager.GetString("msgConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn hủy đơn?.
        /// </summary>
        public static string msgConfirmCancelOrder {
            get {
                return ResourceManager.GetString("msgConfirmCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn thay đổi mật khẩu?.
        /// </summary>
        public static string msgConfirmChangePassword {
            get {
                return ResourceManager.GetString("msgConfirmChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã sử dụng! Vui lòng đăng nhập!.
        /// </summary>
        public static string msgConfirmExistAccount {
            get {
                return ResourceManager.GetString("msgConfirmExistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục bị trùng!.
        /// </summary>
        public static string msgConfirmExistCategory {
            get {
                return ResourceManager.GetString("msgConfirmExistCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đã được tạo! Vui lòng chỉnh sửa!.
        /// </summary>
        public static string msgConfirmExistMenuCd {
            get {
                return ResourceManager.GetString("msgConfirmExistMenuCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn chỉnh sửa thông tin cho đơn hàng?.
        /// </summary>
        public static string msgConfirmUpdateInfo {
            get {
                return ResourceManager.GetString("msgConfirmUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm ghi chú cho đơn hàng?.
        /// </summary>
        public static string msgConfirmUpdateNote {
            get {
                return ResourceManager.GetString("msgConfirmUpdateNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn chuyển trạng thái đơn hàng?.
        /// </summary>
        public static string msgConfirmUpdateStatus {
            get {
                return ResourceManager.GetString("msgConfirmUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email chưa được đăng ký! Vui lòng đăng ký!.
        /// </summary>
        public static string msgEmailNotExist {
            get {
                return ResourceManager.GetString("msgEmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có phản hồi từ server!.
        /// </summary>
        public static string msgErrorWhenCheckExist {
            get {
                return ResourceManager.GetString("msgErrorWhenCheckExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới phải khác mật khẩu cũ!.
        /// </summary>
        public static string PasswordNotChanged {
            get {
                return ResourceManager.GetString("PasswordNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không khớp nhau!.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thanh toán cho đơn hàng!.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đăng kí thành công! Vui lòng đăng nhập!.
        /// </summary>
        public static string RegisterAccountSuccess {
            get {
                return ResourceManager.GetString("RegisterAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công!.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra email để xác nhận tài khoản!.
        /// </summary>
        public static string RegisterWaitEmail {
            get {
                return ResourceManager.GetString("RegisterWaitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại!.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công!.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
