//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Gio_Cha.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SideMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SideMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Gio_Cha.Resources.SideMenu", typeof(SideMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số 43, lô 17 DV Hà Trì, Hà Cầu, Hà đông, Hà Nội.
        /// </summary>
        public static string CompanyAdress {
            get {
                return ResourceManager.GetString("CompanyAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duhochmc@gmail.com.
        /// </summary>
        public static string CompanyEmail {
            get {
                return ResourceManager.GetString("CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty TNHH đầu tư và phát triển dịch vụ HMC.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0982.489.392.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty TNHH đầu tư và phát triển dịch vụ HMC là công ty chuyênTư vấn du học và xuất khẩu lao động Nhật Bản, Hàn Quốc, Đài Loan... Liên kết với các công ty nhằm hỗ trợ việc làm trong và ngoài nước..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du học HMC cung câp dịch vụ tư vấn du học Nhật Bản, tư vấn việc làm, tư vấn xuất khẩu lao động, hỗ trợ việc làm khi về nước.
        /// </summary>
        public static string KeyWordSEO {
            get {
                return ResourceManager.GetString("KeyWordSEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí banner.
        /// </summary>
        public static string ManageBanner {
            get {
                return ResourceManager.GetString("ManageBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Loại Sản phẩm.
        /// </summary>
        public static string ManageCategory {
            get {
                return ResourceManager.GetString("ManageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí giá vận chuyển.
        /// </summary>
        public static string ManageCityPrice {
            get {
                return ResourceManager.GetString("ManageCityPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí tin tức.
        /// </summary>
        public static string ManageNews {
            get {
                return ResourceManager.GetString("ManageNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí đơn hàng.
        /// </summary>
        public static string ManageOrder {
            get {
                return ResourceManager.GetString("ManageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí trang.
        /// </summary>
        public static string ManagePage {
            get {
                return ResourceManager.GetString("ManagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Sản phẩm.
        /// </summary>
        public static string ManageProduct {
            get {
                return ResourceManager.GetString("ManageProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý người dùng.
        /// </summary>
        public static string ManageUser {
            get {
                return ResourceManager.GetString("ManageUser", resourceCulture);
            }
        }
    }
}
